import type { UserGraphData } from './types';

export const mockUsers: UserGraphData[] = [
  {
    userId: 'u1',
    username: 'u1',
    nodes: [
      { id: 'u1', type: 'user', label: 'Alex Rivera', subtitle: 'Highly active user', val: 12 },
      { id: 'g1', type: 'group', label: 'Fitness Community', subtitle: 'Most active category', val: 8 },
      { id: 'g2', type: 'group', label: 'Weekend Hikers', subtitle: 'Local hiking group', val: 5 },
      { id: 'p1', type: 'post', label: '5K Personal Best', subtitle: 'Posted 2 days ago', val: 4 },
      { id: 'p2', type: 'post', label: 'Trail Photos', subtitle: 'Posted 1 week ago', val: 3 },
      { id: 'p3', type: 'post', label: 'Gear Review', subtitle: 'Posted 3 weeks ago', val: 2 },
      { id: 'r1', type: 'reel', label: 'Morning Run Reel', subtitle: '12k views', val: 6 },
      { id: 'r2', type: 'reel', label: 'Cooking Reel', subtitle: '3k views', val: 3 },
      { id: 's1', type: 'status', label: 'Feeling motivated!', subtitle: 'Active 1h ago', val: 2 },
      { id: 'f1', type: 'follower', label: 'Jamie Chen', subtitle: 'Mutual follower', val: 3 },
      { id: 'f2', type: 'follower', label: 'Sam Patel', subtitle: 'Mutual follower', val: 3 },
      { id: 'f3', type: 'follower', label: 'Morgan Lee', subtitle: 'Follower', val: 2 },
      { id: 'm1', type: 'minigame', label: 'Trivia Night', subtitle: 'Top 10 finish', val: 4 },
      { id: 'm2', type: 'minigame', label: 'Word Sprint', subtitle: 'Played 5 times', val: 2 },
    ],
    edges: [
      { source: 'u1', target: 'g1', strength: 0.9 },
      { source: 'u1', target: 'g2', strength: 0.5 },
      { source: 'u1', target: 'p1', strength: 0.8 },
      { source: 'u1', target: 'p2', strength: 0.4 },
      { source: 'u1', target: 'p3', strength: 0.3 },
      { source: 'u1', target: 'r1', strength: 0.85 },
      { source: 'u1', target: 'r2', strength: 0.35 },
      { source: 'u1', target: 's1', strength: 0.25 },
      { source: 'u1', target: 'f1', strength: 0.7 },
      { source: 'u1', target: 'f2', strength: 0.6 },
      { source: 'u1', target: 'f3', strength: 0.2 },
      { source: 'u1', target: 'm1', strength: 0.75 },
      { source: 'u1', target: 'm2', strength: 0.3 },
      { source: 'g1', target: 'p1', strength: 0.4 },
      { source: 'g2', target: 'p2', strength: 0.3 },
    ],
  },
  {
    userId: 'u2',
    username: 'u2',
    nodes: [
      { id: 'u2', type: 'user', label: 'Jordan Kim', subtitle: 'Mid-activity user', val: 10 },
      { id: 'g3', type: 'group', label: 'Book Club', subtitle: 'Most active category', val: 6 },
      { id: 'p4', type: 'post', label: 'Book Review: Dune', subtitle: 'Posted 4 days ago', val: 3 },
      { id: 's2', type: 'status', label: 'Reading all weekend', subtitle: 'Active 5h ago', val: 2 },
      { id: 'f4', type: 'follower', label: 'Taylor Brooks', subtitle: 'Mutual follower', val: 3 },
      { id: 'f5', type: 'follower', label: 'Casey Nguyen', subtitle: 'Follower', val: 2 },
    ],
    edges: [
      { source: 'u2', target: 'g3', strength: 0.75 },
      { source: 'u2', target: 'p4', strength: 0.5 },
      { source: 'u2', target: 's2', strength: 0.3 },
      { source: 'u2', target: 'f4', strength: 0.65 },
      { source: 'u2', target: 'f5', strength: 0.35 },
      { source: 'g3', target: 'p4', strength: 0.4 },
    ],
  },
  {
    userId: 'u3',
    username: 'u3',
    nodes: [
      { id: 'u3', type: 'user', label: 'Priya Singh', subtitle: 'Low-activity user', val: 8 },
      { id: 'f6', type: 'follower', label: 'Devon Ward', subtitle: 'Follower', val: 2 },
      { id: 's3', type: 'status', label: 'Back from vacation', subtitle: 'Active 2d ago', val: 2 },
    ],
    edges: [
      { source: 'u3', target: 'f6', strength: 0.3 },
      { source: 'u3', target: 's3', strength: 0.2 },
    ],
  },
  {
    userId: 'u5',
    username: 'u5',
    nodes: [
      { id: 'u5', type: 'user', label: 'Ella Novak', subtitle: 'Highly active user', val: 12 },
      { id: 'g6', type: 'group', label: 'Urban Sketchers', subtitle: 'Most active category', val: 8 },
      { id: 'g7', type: 'group', label: 'Plant Parents', subtitle: 'Secondary group', val: 5 },
      { id: 'g8', type: 'group', label: 'Coffee Enthusiasts', subtitle: 'Casual group', val: 3 },
      { id: 'p5', type: 'post', label: 'Sunday Sketch Dump', subtitle: 'Posted 1 day ago', val: 4 },
      { id: 'p6', type: 'post', label: 'New Monstera Leaf', subtitle: 'Posted 6 days ago', val: 3 },
      { id: 'p7', type: 'post', label: 'Latte Art Attempt #4', subtitle: 'Posted 2 weeks ago', val: 2 },
      { id: 'r4', type: 'reel', label: 'Speedpaint Timelapse', subtitle: '20k views', val: 7 },
      { id: 'r5', type: 'reel', label: 'Studio Tour', subtitle: '5k views', val: 3 },
      { id: 's4', type: 'status', label: 'Gallery opening tonight!', subtitle: 'Active 30m ago', val: 2 },
      { id: 'f8', type: 'follower', label: 'Rosa Kim', subtitle: 'Mutual follower', val: 3 },
      { id: 'f9', type: 'follower', label: 'Theo Brandt', subtitle: 'Mutual follower', val: 3 },
      { id: 'f10', type: 'follower', label: 'Ines Duarte', subtitle: 'Follower', val: 2 },
      { id: 'f11', type: 'follower', label: 'Marcus Dean', subtitle: 'Follower', val: 2 },
      { id: 'm5', type: 'minigame', label: 'Color Match', subtitle: 'High score holder', val: 4 },
      { id: 'm6', type: 'minigame', label: 'Trivia Night', subtitle: 'Played 3 times', val: 2 },
    ],
    edges: [
      { source: 'u5', target: 'g6', strength: 0.9 },
      { source: 'u5', target: 'g7', strength: 0.55 },
      { source: 'u5', target: 'g8', strength: 0.3 },
      { source: 'u5', target: 'p5', strength: 0.8 },
      { source: 'u5', target: 'p6', strength: 0.45 },
      { source: 'u5', target: 'p7', strength: 0.25 },
      { source: 'u5', target: 'r4', strength: 0.85 },
      { source: 'u5', target: 'r5', strength: 0.4 },
      { source: 'u5', target: 's4', strength: 0.3 },
      { source: 'u5', target: 'f8', strength: 0.7 },
      { source: 'u5', target: 'f9', strength: 0.65 },
      { source: 'u5', target: 'f10', strength: 0.3 },
      { source: 'u5', target: 'f11', strength: 0.2 },
      { source: 'u5', target: 'm5', strength: 0.6 },
      { source: 'u5', target: 'm6', strength: 0.3 },
      { source: 'g6', target: 'p5', strength: 0.4 },
      { source: 'g7', target: 'p6', strength: 0.35 },
    ],
  },
  {
    userId: 'u6',
    username: 'u6',
    nodes: [
      { id: 'u6', type: 'user', label: 'Ravi Kapoor', subtitle: 'Low-activity user', val: 8 },
      { id: 'p8', type: 'post', label: 'New Apartment Tour', subtitle: 'Posted 5 days ago', val: 3 },
      { id: 'f12', type: 'follower', label: 'Anya Fischer', subtitle: 'Follower', val: 2 },
    ],
    edges: [
      { source: 'u6', target: 'p8', strength: 0.4 },
      { source: 'u6', target: 'f12', strength: 0.25 },
    ],
  },
  {
    userId: 'u7',
    username: 'u7',
    nodes: [
      { id: 'u7', type: 'user', label: 'Lena Moreau', subtitle: 'Mid-activity user', val: 10 },
      { id: 'g9', type: 'group', label: 'Language Exchange', subtitle: 'Most active category', val: 6 },
      { id: 'r6', type: 'reel', label: 'French Vlog #3', subtitle: '9k views', val: 5 },
      { id: 's5', type: 'status', label: 'Studying for exams', subtitle: 'Active 3h ago', val: 2 },
      { id: 'f13', type: 'follower', label: 'Owen Brady', subtitle: 'Mutual follower', val: 3 },
      { id: 'f14', type: 'follower', label: 'Priya Singh', subtitle: 'Follower', val: 2 },
      { id: 'm7', type: 'minigame', label: 'Word Sprint', subtitle: 'High score holder', val: 4 },
    ],
    edges: [
      { source: 'u7', target: 'g9', strength: 0.75 },
      { source: 'u7', target: 'r6', strength: 0.6 },
      { source: 'u7', target: 's5', strength: 0.3 },
      { source: 'u7', target: 'f13', strength: 0.65 },
      { source: 'u7', target: 'f14', strength: 0.25 },
      { source: 'u7', target: 'm7', strength: 0.55 },
      { source: 'g9', target: 'r6', strength: 0.3 },
    ],
  },
  {
    userId: 'u8',
    username: 'u8',
    nodes: [
      { id: 'u8', type: 'user', label: 'Zoe Bennett', subtitle: 'Low-activity user', val: 8 },
      { id: 's6', type: 'status', label: 'New job, new city', subtitle: 'Active 1d ago', val: 2 },
    ],
    edges: [{ source: 'u8', target: 's6', strength: 0.2 }],
  },
  {
    userId: 'u4',
    username: 'u4',
    nodes: [
      { id: 'u4', type: 'user', label: 'Marcus Dean', subtitle: 'Mid-activity user', val: 10 },
      { id: 'g4', type: 'group', label: 'Indie Game Devs', subtitle: 'Most active category', val: 6 },
      { id: 'g5', type: 'group', label: 'Retro Arcade Fans', subtitle: 'Secondary group', val: 4 },
      { id: 'r3', type: 'reel', label: 'Devlog #12', subtitle: '8k views', val: 5 },
      { id: 'm3', type: 'minigame', label: 'Pixel Puzzle', subtitle: 'High score holder', val: 4 },
      { id: 'm4', type: 'minigame', label: 'Speed Chess', subtitle: 'Played 2 times', val: 2 },
      { id: 'f7', type: 'follower', label: 'Nina Osei', subtitle: 'Mutual follower', val: 3 },
    ],
    edges: [
      { source: 'u4', target: 'g4', strength: 0.8 },
      { source: 'u4', target: 'g5', strength: 0.45 },
      { source: 'u4', target: 'r3', strength: 0.7 },
      { source: 'u4', target: 'm3', strength: 0.6 },
      { source: 'u4', target: 'm4', strength: 0.3 },
      { source: 'u4', target: 'f7', strength: 0.55 },
      { source: 'g4', target: 'r3', strength: 0.35 },
    ],
  },
];
